/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StencilRoot {}
  interface StencilRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'StencilRoot': Components.StencilRoot;
  }

  interface StencilIntrinsicElements {
    'stencil-root': Components.StencilRootAttributes;
  }


  interface HTMLStencilRootElement extends Components.StencilRoot, HTMLStencilElement {}
  var HTMLStencilRootElement: {
    prototype: HTMLStencilRootElement;
    new (): HTMLStencilRootElement;
  };

  interface HTMLElementTagNameMap {
    'stencil-root': HTMLStencilRootElement
  }

  interface ElementTagNameMap {
    'stencil-root': HTMLStencilRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
